### ISSUE TITLE
Breaks accessed properties

### ISSUE THREAD

**Issue by MolotovCherry** [Mendeo/jekyll-minifier#1]
Title is a bit hard to say, so here's an example

This
```js
elem.addEventListener("click", event => {
  event.currentTarget.classList.toggle("active");
  var content = event.currentTarget.nextElementSibling;
  if (content.style.maxHeight) {
    content.style.maxHeight = null;
  } else {
    content.style.maxHeight = content.scrollHeight + "px";
  }
});
```

Turned into something similar to this as generated code
```js
a.addEventListener("click", event => {
  e.currentTarget.classList.toggle("active");
  var c = e.currentTarget.nextElementSibling;
  // entire c.style.maxHeight is missing, instead is a new variable which doesn't exist
  if (b) {
    // for some reason it also renamed this one too
    b = null;
  } else {
    // and this one
    b = c.scrollHeight + "px";
  }
});
```

The workaround is to assign the accessed property thing to a new variable in order to make the minifier ignore the inside ones and actually assign to it.
```js
elem.addEventListener("click", event => {
  event.currentTarget.classList.toggle("active");
  var content = event.currentTarget.nextElementSibling;
  // fix bug in minifier which shortened this to only one var
  var height = content.style.maxHeight;
  
  if (height) {
    content.style.maxHeight = null;
  } else {
    content.style.maxHeight = content.scrollHeight + "px";
  }
});
```

**Comment by Mendeo** [comment]
Hi!
I can't reproduce the bug.
This code
```javascript
---
layout: js_minifier
---
const elem = {};
elem.addEventListener("click", event => {
	event.currentTarget.classList.toggle("active");
	var content = event.currentTarget.nextElementSibling;
	if (content.style.maxHeight) {
	  content.style.maxHeight = null;
	} else {
	  content.style.maxHeight = content.scrollHeight + "px";
	}
  });
```
gives me
```javascript
const d={};d.addEventListener("click",c=>{c.currentTarget.classList.toggle("active");var b=c.currentTarget.nextElementSibling;if(b.style.maxHeight){b.style.maxHeight=null;}else{b.style.maxHeight=b.scrollHeight+"px";}});
```
Maybe something else in your code is causing this bug.

**Comment by MolotovCherry** [comment]
That's unfortunate. I was hoping the minimal example would suffice without needing to provide the whole thing to trigger the bug. Here's a permalink to the line+entire file which I know for sure did cause it (and continues to cause it when I test it)
https://github.com/cherryleafroad/cherryleafroad.github.io/blob/e0ba3b4744b7d56a95a417e28d972a7e2a8dad0e/assets/js/deferred.js#L55

I first tried with the function only, and the output is fine, but when I do the entire file, then this bug happens there. Not sure exactly what's causing it.

What I do know:
\- The `collapseCodeBlocks()` by itself isn't causing it
\- Something after that is causing it (or interacting negatively with that function)

**Comment by Mendeo** [comment]
I found the error and fixed it. You can try update js_minifier now.
Thank you.
