### ISSUE TITLE
No space between attributes (links become unclickable)

### ISSUE THREAD

**Issue by igorfree** [Mendeo/jekyll-minifier#3]
After minification my HTML code becomes invalid. There are also display problems inside my browser (a link becomes unclickable, just text).

Here is how jekyll generated my static HTML code without minification (it is a language switch, with lots of liquid used inside the template, which is the reason for multiple spaces and newlines):

```
    <li>
      <a  style="text-decoration: none;" class="activeLang" 
	 href="/"
	        
	  title="Deutsch" 
	 >de</a> </li>
    
    <li>
      <a 
	 href="/en/"
	  title="Englisch"        
	 
	 >en</a> </li>
    
    <li>
```

Here how the same spot looks after minification: 
```
<li><a  style="text-decoration: none;" class="activeLang"href="/"title="Deutsch">de</a> </li><li><ahref="/en/"title="Englisch">en</a> </li>
```

As you can see, there are no spaces in between some attributes (class and href, href and title). Even the start of an `<a>`-tag gets mashed together with the href-attribute. This makes the link unclickable and the w3c markup validator also marks this as an error.

Not every single one `<a>`-tag got mishandled this way however. I have several places where `<a href=""...</a>` is nested within a `<ul><li>...</li></ul>`, but only one of the lists is affected by this.

**Comment by Mendeo** [comment]
Hi!
In your case, the solution would be to add to the spaceTags variable (the second line of code after the license) all the tags (separated by a space) in which such transfers of attributes to another line occur. For your example, the line would be: {%- assign spaceTags = "a p" | split: " " -%} (added tag "a"). I've adjusted the code a bit for these cases to remove some double spaces, but sometimes extra spaces happen.
